import { Car } from "@/components/car-card"

export const cars: Car[] = [
  // BMW Models
  {
    id: "bmw-m5",
    name: "BMW M5",
    brand: "BMW",
    image: "/images/bmw/bmwm5.jpg",
    price: "$103,500",
    engine: "4.4L V8 TwinPower Turbo",
    power: "617 hp",
    acceleration: "0-100 km/h in 3.2 sec",
    mpg: "15.7 L/100km city / 11.2 L/100km highway",
    description: "The BMW M5 combines luxury with high performance, featuring a powerful V8 engine and advanced driving technologies.",
    features: [
      "M xDrive all-wheel drive",
      "8-speed M Steptronic transmission",
      "20-inch M light-alloy wheels",
      "M Sport brakes",
      "Merino leather upholstery",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "Active M Differential"
    ]
  },
  {
    id: "bmw-x3",
    name: "BMW X3",
    brand: "BMW",
    image: "/images/bmw/bmwx3.jpg",
    price: "$43,700",
    engine: "2.0L Inline-4 Turbo",
    power: "248 hp",
    acceleration: "0-100 km/h in 6.0 sec",
    mpg: "10.2 L/100km city / 7.8 L/100km highway",
    description: "The BMW X3 is a versatile compact SUV that offers a perfect blend of luxury, comfort, and performance.",
    features: [
      "xDrive all-wheel drive",
      "8-speed automatic transmission",
      "Live Cockpit Professional",
      "Panoramic moonroof",
      "Power tailgate",
      "Parking Assistant",
      "Driving Assistant Professional",
      "Comfort Access keyless entry"
    ]
  },
  {
    id: "bmw-x3m",
    name: "BMW X3 M",
    brand: "BMW",
    image: "/images/bmw/bmwx3m.jpg",
    price: "$72,800",
    engine: "3.0L Inline-6 TwinPower Turbo",
    power: "473 hp",
    acceleration: "0-100 km/h in 4.1 sec",
    mpg: "14.7 L/100km city / 12.4 L/100km highway",
    description: "The BMW X3 M delivers exceptional performance with M-specific engineering and design elements.",
    features: [
      "M xDrive all-wheel drive",
      "8-speed M Steptronic transmission",
      "M Sport exhaust system",
      "M Sport brakes",
      "M Sport seats",
      "M Sport steering wheel",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound"
    ]
  },
  {
    id: "bmw-x4",
    name: "BMW X4",
    brand: "BMW",
    image: "/images/bmw/bmwx4.jpg",
    price: "$52,100",
    engine: "2.0L Inline-4 Turbo",
    power: "248 hp",
    acceleration: "0-100 km/h in 6.0 sec",
    mpg: "10.2 L/100km city / 7.8 L/100km highway",
    description: "The BMW X4 combines the versatility of an SUV with the sporty design of a coupe.",
    features: [
      "xDrive all-wheel drive",
      "8-speed automatic transmission",
      "Live Cockpit Professional",
      "Panoramic moonroof",
      "Power tailgate",
      "Parking Assistant",
      "Driving Assistant Professional",
      "Comfort Access keyless entry"
    ]
  },
  {
    id: "bmw-x4m",
    name: "BMW X4 M",
    brand: "BMW",
    image: "/images/bmw/bmwx4m.jpg",
    price: "$74,800",
    engine: "3.0L Inline-6 TwinPower Turbo",
    power: "473 hp",
    acceleration: "0-100 km/h in 4.1 sec",
    mpg: "14.7 L/100km city / 12.4 L/100km highway",
    description: "The BMW X4 M combines the coupe-like design of the X4 with M performance capabilities.",
    features: [
      "M xDrive all-wheel drive",
      "8-speed M Steptronic transmission",
      "M Sport exhaust system",
      "M Sport brakes",
      "M Sport seats",
      "M Sport steering wheel",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound"
    ]
  },
  {
    id: "bmw-x5",
    name: "BMW X5",
    brand: "BMW",
    image: "/images/bmw/bmwx5.jpg",
    price: "$61,600",
    engine: "3.0L Inline-6 Turbo",
    power: "335 hp",
    acceleration: "0-100 km/h in 5.3 sec",
    mpg: "11.2 L/100km city / 9.0 L/100km highway",
    description: "The BMW X5 is a luxury SUV that combines comfort, versatility, and performance in a sophisticated package.",
    features: [
      "xDrive all-wheel drive",
      "8-speed automatic transmission",
      "Live Cockpit Professional",
      "Panoramic moonroof",
      "Power tailgate",
      "Parking Assistant Plus",
      "Driving Assistant Professional",
      "Comfort Access keyless entry"
    ]
  },
  {
    id: "bmw-x5m",
    name: "BMW X5 M",
    brand: "BMW",
    image: "/images/bmw/bmwx5m.jpg",
    price: "$105,100",
    engine: "4.4L V8 TwinPower Turbo",
    power: "600 hp",
    acceleration: "0-100 km/h in 3.8 sec",
    mpg: "18.1 L/100km city / 13.1 L/100km highway",
    description: "The BMW X5 M delivers exceptional performance with M-specific engineering and design elements.",
    features: [
      "M xDrive all-wheel drive",
      "8-speed M Steptronic transmission",
      "M Sport exhaust system",
      "M Sport brakes",
      "M Sport seats",
      "M Sport steering wheel",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound"
    ]
  },
  {
    id: "bmw-x6",
    name: "BMW X6",
    brand: "BMW",
    image: "/images/bmw/bmwx6.jpg",
    price: "$65,600",
    engine: "3.0L Inline-6 Turbo",
    power: "335 hp",
    acceleration: "0-100 km/h in 5.3 sec",
    mpg: "11.2 L/100km city / 9.0 L/100km highway",
    description: "The BMW X6 combines the versatility of an SUV with the sporty design of a coupe.",
    features: [
      "xDrive all-wheel drive",
      "8-speed automatic transmission",
      "Live Cockpit Professional",
      "Panoramic moonroof",
      "Power tailgate",
      "Parking Assistant Plus",
      "Driving Assistant Professional",
      "Comfort Access keyless entry"
    ]
  },
  {
    id: "bmw-x6m",
    name: "BMW X6 M",
    brand: "BMW",
    image: "/images/bmw/bmwx6m.jpg",
    price: "$107,100",
    engine: "4.4L V8 TwinPower Turbo",
    power: "600 hp",
    acceleration: "0-100 km/h in 3.8 sec",
    mpg: "18.1 L/100km city / 13.1 L/100km highway",
    description: "The BMW X6 M combines the coupe-like design of the X6 with M performance capabilities.",
    features: [
      "M xDrive all-wheel drive",
      "8-speed M Steptronic transmission",
      "M Sport exhaust system",
      "M Sport brakes",
      "M Sport seats",
      "M Sport steering wheel",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound"
    ]
  },
  {
    id: "bmw-x7",
    name: "BMW X7",
    brand: "BMW",
    image: "/images/bmw/bmwx7.jpg",
    price: "$77,850",
    engine: "3.0L Inline-6 Turbo",
    power: "375 hp",
    acceleration: "0-100 km/h in 5.8 sec",
    mpg: "11.8 L/100km city / 9.4 L/100km highway",
    description: "The BMW X7 is the largest and most luxurious SUV in the BMW lineup, offering three rows of seating and premium features.",
    features: [
      "xDrive all-wheel drive",
      "8-speed automatic transmission",
      "Air suspension",
      "Panoramic Sky Lounge LED roof",
      "Executive package",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "Gesture Control"
    ]
  },
  {
    id: "bmw-er2",
    name: "BMW iX2",
    brand: "BMW",
    image: "/images/bmw/bmwer2.jpg",
    price: "$52,200",
    engine: "Dual Electric Motors",
    power: "313 hp",
    acceleration: "0-100 km/h in 5.6 sec",
    mpg: "N/A",
    description: "The BMW iX2 is an all-electric compact SUV that combines sustainable mobility with BMW's signature driving dynamics.",
    features: [
      "All-wheel drive",
      "Single-speed transmission",
      "BMW Operating System 8.5",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric",
      "BMW Charging",
      "BMW eDrive Zone"
    ]
  },
  {
    id: "bmw-er3",
    name: "BMW iX3",
    brand: "BMW",
    image: "/images/bmw/bmwer3.jpg",
    price: "$52,200",
    engine: "Electric Motor",
    power: "286 hp",
    acceleration: "0-100 km/h in 6.8 sec",
    mpg: "N/A",
    description: "The BMW iX3 is an all-electric compact SUV that offers sustainable mobility without compromising on luxury and performance.",
    features: [
      "Rear-wheel drive",
      "Single-speed transmission",
      "BMW Operating System 8.5",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric",
      "BMW Charging",
      "BMW eDrive Zone"
    ]
  },
  {
    id: "bmw-er3m",
    name: "BMW iX3 M",
    brand: "BMW",
    image: "/images/bmw/bmwer3m.jpg",
    price: "$72,800",
    engine: "Dual Electric Motors",
    power: "516 hp",
    acceleration: "0-100 km/h in 3.8 sec",
    mpg: "N/A",
    description: "The BMW iX3 M combines M performance with sustainable electric mobility.",
    features: [
      "M xDrive all-wheel drive",
      "M Sport suspension",
      "M Sport brakes",
      "M Sport seats",
      "M Sport steering wheel",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric"
    ]
  },
  {
    id: "bmw-er4",
    name: "BMW i4",
    brand: "BMW",
    image: "/images/bmw/bmwer4.jpg",
    price: "$52,200",
    engine: "Electric Motor",
    power: "340 hp",
    acceleration: "0-100 km/h in 5.5 sec",
    mpg: "N/A",
    description: "The BMW i4 is an all-electric gran coupe that combines sustainable mobility with BMW's signature driving dynamics.",
    features: [
      "Rear-wheel drive",
      "Single-speed transmission",
      "BMW Operating System 8.5",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric",
      "BMW Charging",
      "BMW eDrive Zone"
    ]
  },
  {
    id: "bmw-er4m",
    name: "BMW i4 M",
    brand: "BMW",
    image: "/images/bmw/bmwer4m.jpg",
    price: "$72,800",
    engine: "Dual Electric Motors",
    power: "536 hp",
    acceleration: "0-100 km/h in 3.9 sec",
    mpg: "N/A",
    description: "The BMW i4 M combines M performance with sustainable electric mobility.",
    features: [
      "M xDrive all-wheel drive",
      "M Sport suspension",
      "M Sport brakes",
      "M Sport seats",
      "M Sport steering wheel",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric"
    ]
  },
  {
    id: "bmw-er4cupe",
    name: "BMW i4 Coupe",
    brand: "BMW",
    image: "/images/bmw/bmwer4cupe.jpg",
    price: "$52,200",
    engine: "Electric Motor",
    power: "340 hp",
    acceleration: "0-100 km/h in 5.5 sec",
    mpg: "N/A",
    description: "The BMW i4 Coupe is an all-electric coupe that combines sustainable mobility with BMW's signature driving dynamics.",
    features: [
      "Rear-wheel drive",
      "Single-speed transmission",
      "BMW Operating System 8.5",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric",
      "BMW Charging",
      "BMW eDrive Zone"
    ]
  },
  {
    id: "bmw-er7",
    name: "BMW i7",
    brand: "BMW",
    image: "/images/bmw/bmwer7.jpg",
    price: "$119,300",
    engine: "Dual Electric Motors",
    power: "536 hp",
    acceleration: "0-100 km/h in 4.7 sec",
    mpg: "N/A",
    description: "The BMW i7 is an all-electric luxury sedan that combines sustainable mobility with BMW's signature luxury and performance.",
    features: [
      "All-wheel drive",
      "Single-speed transmission",
      "BMW Operating System 8.5",
      "BMW Live Cockpit Professional",
      "Bowers & Wilkins surround sound",
      "BMW IconicSounds Electric",
      "BMW Charging",
      "BMW eDrive Zone"
    ]
  },
  {
    id: "bmw-er7m",
    name: "BMW i7 M",
    brand: "BMW",
    image: "/images/bmw/bmwer7m.jpg",
    price: "$142,800",
    engine: "Dual Electric Motors",
    power: "650 hp",
    acceleration: "0-100 km/h in 3.7 sec",
    mpg: "N/A",
    description: "The BMW i7 M combines M performance with sustainable electric mobility in a luxury sedan package.",
    features: [
      "M xDrive all-wheel drive",
      "M Sport suspension",
      "M Sport brakes",
      "M Sport seats",
      "M Sport steering wheel",
      "BMW Live Cockpit Professional",
      "Bowers & Wilkins surround sound",
      "BMW IconicSounds Electric"
    ]
  },
  {
    id: "bmw-er8coupe",
    name: "BMW i8 Coupe",
    brand: "BMW",
    image: "/images/bmw/bmwer8coupe.jpg",
    price: "$147,500",
    engine: "Hybrid",
    power: "369 hp",
    acceleration: "0-100 km/h in 4.4 sec",
    mpg: "N/A",
    description: "The BMW i8 Coupe is a hybrid sports car that combines sustainable mobility with BMW's signature driving dynamics.",
    features: [
      "All-wheel drive",
      "6-speed automatic transmission",
      "BMW Operating System 8.5",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric",
      "BMW Charging",
      "BMW eDrive Zone"
    ]
  },
  {
    id: "bmw-er8m",
    name: "BMW i8 M",
    brand: "BMW",
    image: "/images/bmw/bmwer8m.jpg",
    price: "$157,500",
    engine: "Hybrid",
    power: "455 hp",
    acceleration: "0-100 km/h in 3.8 sec",
    mpg: "N/A",
    description: "The BMW i8 M combines M performance with sustainable hybrid mobility in a sports car package.",
    features: [
      "M xDrive all-wheel drive",
      "M Sport suspension",
      "M Sport brakes",
      "M Sport seats",
      "M Sport steering wheel",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric"
    ]
  },
  {
    id: "bmw-er8carbio",
    name: "BMW i8 Cabriolet",
    brand: "BMW",
    image: "/images/bmw/bmwer8carbio.jpg",
    price: "$163,300",
    engine: "Hybrid",
    power: "369 hp",
    acceleration: "0-100 km/h in 4.4 sec",
    mpg: "N/A",
    description: "The BMW i8 Cabriolet is a hybrid sports car that combines sustainable mobility with BMW's signature driving dynamics and open-top motoring.",
    features: [
      "All-wheel drive",
      "6-speed automatic transmission",
      "BMW Operating System 8.5",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound",
      "BMW IconicSounds Electric",
      "BMW Charging",
      "BMW eDrive Zone"
    ]
  },

  // Audi Models
  {
    id: "audi-a3",
    name: "Audi A3",
    brand: "Audi",
    image: "/images/audi/audia3.jpg",
    price: "$34,800",
    engine: "2.0L Inline-4 Turbo",
    power: "201 hp",
    acceleration: "0-100 km/h in 6.8 sec",
    mpg: "8.7 L/100km city / 6.5 L/100km highway",
    description: "The Audi A3 is a premium compact car that combines sophisticated design with dynamic performance.",
    features: [
      "Front-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-a4",
    name: "Audi A4",
    brand: "Audi",
    image: "/images/audi/audia4.jpg",
    price: "$39,900",
    engine: "2.0L Inline-4 Turbo",
    power: "261 hp",
    acceleration: "0-100 km/h in 5.5 sec",
    mpg: "9.8 L/100km city / 7.6 L/100km highway",
    description: "The Audi A4 is a premium sedan that combines sophisticated design with dynamic performance.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-a5",
    name: "Audi A5",
    brand: "Audi",
    image: "/images/audi/audia5.jpg",
    price: "$44,000",
    engine: "2.0L Inline-4 Turbo",
    power: "261 hp",
    acceleration: "0-100 km/h in 5.3 sec",
    mpg: "9.8 L/100km city / 7.6 L/100km highway",
    description: "The Audi A5 combines sophisticated design with dynamic performance in a premium coupe package.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-a6",
    name: "Audi A6",
    brand: "Audi",
    image: "/images/audi/audia6.jpg",
    price: "$54,900",
    engine: "2.0L Inline-4 Turbo",
    power: "261 hp",
    acceleration: "0-100 km/h in 5.8 sec",
    mpg: "10.2 L/100km city / 7.8 L/100km highway",
    description: "The Audi A6 is a premium sedan that combines sophisticated design with dynamic performance.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-a8",
    name: "Audi A8",
    brand: "Audi",
    image: "/images/audi/audia8.jpg",
    price: "$86,500",
    engine: "3.0L V6 Turbo",
    power: "335 hp",
    acceleration: "0-100 km/h in 5.3 sec",
    mpg: "11.2 L/100km city / 8.4 L/100km highway",
    description: "The Audi A8 is a luxury sedan that combines sophisticated design with dynamic performance.",
    features: [
      "quattro all-wheel drive",
      "8-speed automatic transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-tt",
    name: "Audi TT",
    brand: "Audi",
    image: "/images/audi/auditt.jpg",
    price: "$54,900",
    engine: "2.0L Inline-4 Turbo",
    power: "228 hp",
    acceleration: "0-100 km/h in 5.3 sec",
    mpg: "9.8 L/100km city / 7.6 L/100km highway",
    description: "The Audi TT is a premium sports car that combines sophisticated design with dynamic performance.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-q3",
    name: "Audi Q3",
    brand: "Audi",
    image: "/images/audi/audiq3.jpg",
    price: "$36,800",
    engine: "2.0L Inline-4 Turbo",
    power: "228 hp",
    acceleration: "0-100 km/h in 6.3 sec",
    mpg: "10.2 L/100km city / 7.8 L/100km highway",
    description: "The Audi Q3 is a premium compact SUV that combines sophisticated design with dynamic performance.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-q4etron",
    name: "Audi Q4 e-tron",
    brand: "Audi",
    image: "/images/audi/audiq4etron.jpg",
    price: "$49,800",
    engine: "Dual Electric Motors",
    power: "295 hp",
    acceleration: "0-100 km/h in 6.2 sec",
    mpg: "N/A",
    description: "The Audi Q4 e-tron is an all-electric compact SUV that combines sophisticated design with sustainable mobility.",
    features: [
      "quattro all-wheel drive",
      "Single-speed transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-q5",
    name: "Audi Q5",
    brand: "Audi",
    image: "/images/audi/audiq5.jpg",
    price: "$43,500",
    engine: "2.0L Inline-4 Turbo",
    power: "261 hp",
    acceleration: "0-100 km/h in 5.7 sec",
    mpg: "10.2 L/100km city / 8.4 L/100km highway",
    description: "The Audi Q5 is a premium compact SUV that offers a perfect blend of luxury, comfort, and performance.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Panoramic sunroof",
      "Audi MMI touch response system",
      "Adaptive cruise control",
      "Virtual cockpit plus",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems"
    ]
  },
  {
    id: "audi-q8",
    name: "Audi Q8",
    brand: "Audi",
    image: "/images/audi/audiq8.jpg",
    price: "$68,200",
    engine: "3.0L V6 Turbo",
    power: "335 hp",
    acceleration: "0-100 km/h in 5.6 sec",
    mpg: "11.2 L/100km city / 8.4 L/100km highway",
    description: "The Audi Q8 is a premium SUV that combines sophisticated design with dynamic performance.",
    features: [
      "quattro all-wheel drive",
      "8-speed automatic transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-q8etron",
    name: "Audi Q8 e-tron",
    brand: "Audi",
    image: "/images/audi/audiq8etron.jpg",
    price: "$74,400",
    engine: "Dual Electric Motors",
    power: "402 hp",
    acceleration: "0-100 km/h in 5.6 sec",
    mpg: "N/A",
    description: "The Audi Q8 e-tron is an all-electric SUV that combines sophisticated design with sustainable mobility.",
    features: [
      "quattro all-wheel drive",
      "Single-speed transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },
  {
    id: "audi-r8",
    name: "Audi R8",
    brand: "Audi",
    image: "/images/audi/audir8.jpg",
    price: "$142,700",
    engine: "5.2L V10",
    power: "562 hp",
    acceleration: "0-100 km/h in 3.6 sec",
    mpg: "16.8 L/100km city / 10.2 L/100km highway",
    description: "The Audi R8 is a high-performance supercar that delivers exceptional power and precision.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Carbon fiber and aluminum construction",
      "Virtual cockpit",
      "Magnetic ride suspension",
      "Carbon ceramic brakes",
      "Bang & Olufsen sound system",
      "Audi laser light"
    ]
  },
  {
    id: "audi-rs7",
    name: "Audi RS7",
    brand: "Audi",
    image: "/images/audi/audirs7.jpg",
    price: "$118,500",
    engine: "4.0L V8 Twin-Turbo",
    power: "591 hp",
    acceleration: "0-100 km/h in 3.5 sec",
    mpg: "15.7 L/100km city / 11.2 L/100km highway",
    description: "The Audi RS7 is a high-performance sportback that delivers exceptional power and precision.",
    features: [
      "quattro all-wheel drive",
      "8-speed automatic transmission",
      "Carbon fiber and aluminum construction",
      "Virtual cockpit",
      "Magnetic ride suspension",
      "Carbon ceramic brakes",
      "Bang & Olufsen sound system",
      "Audi laser light"
    ]
  },
  {
    id: "audi-etron-gt",
    name: "Audi e-tron GT",
    brand: "Audi",
    image: "/images/audi/audietrongt.jpg",
    price: "$102,400",
    engine: "Dual Electric Motors",
    power: "522 hp",
    acceleration: "0-100 km/h in 3.9 sec",
    mpg: "N/A",
    description: "The Audi e-tron GT is a high-performance electric vehicle that combines sustainable mobility with dynamic driving.",
    features: [
      "quattro all-wheel drive",
      "2-speed transmission",
      "Adaptive air suspension",
      "800-volt electrical architecture",
      "93.4 kWh battery capacity",
      "Matrix LED headlights",
      "Bang & Olufsen sound system",
      "Audi virtual cockpit plus"
    ]
  },
  {
    id: "audi-allnewa5",
    name: "Audi All New A5",
    brand: "Audi",
    image: "/images/audi/allnewa5.jpg",
    price: "$44,000",
    engine: "2.0L Inline-4 Turbo",
    power: "261 hp",
    acceleration: "0-100 km/h in 5.3 sec",
    mpg: "9.8 L/100km city / 7.6 L/100km highway",
    description: "The All New Audi A5 combines sophisticated design with dynamic performance in a premium coupe package.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
      "Matrix LED headlights",
      "Panoramic sunroof",
      "Sport suspension"
    ]
  },

  // Toyota Models
  {
    id: "toyota-gr-supra-3.0",
    name: "GR Supra 3.0",
    brand: "Toyota",
    image: "/images/toyota/grsupra3.0.png",
    price: "$56,500",
    engine: "3.0L Inline-6 Turbo",
    power: "382 hp",
    acceleration: "0-100 km/h in 3.9 sec",
    mpg: "10.7 L/100km city / 7.8 L/100km highway",
    description: "The Toyota GR Supra is a legendary sports car that combines heritage with modern performance.",
    features: [
      "Rear-wheel drive",
      "8-speed automatic transmission",
      "Adaptive Variable Sport suspension",
      "Active differential",
      "Brembo 4-piston calipers",
      "JBL premium audio",
      "Supra Command system",
      "Active sound design"
    ]
  },
  {
    id: "toyota-gr-supra-3.0-premium",
    name: "GR Supra 3.0 Premium",
    brand: "Toyota",
    image: "/images/toyota/grsupra3.0-premium.png",
    price: "$58,500",
    engine: "3.0L Inline-6 Turbo",
    power: "382 hp",
    acceleration: "0-100 km/h in 3.9 sec",
    mpg: "10.7 L/100km city / 7.8 L/100km highway",
    description: "The GR Supra 3.0 Premium offers enhanced luxury features while maintaining the same powerful performance.",
    features: [
      "Rear-wheel drive",
      "8-speed automatic transmission",
      "Adaptive Variable Sport suspension",
      "Active differential",
      "Brembo 4-piston calipers",
      "JBL premium audio",
      "Supra Command system",
      "Active sound design",
      "Heated seats",
      "Head-up display"
    ]
  },
  {
    id: "toyota-crown-platinum",
    name: "Crown Platinum",
    brand: "Toyota",
    image: "/images/toyota/crown-platinum.png",
    price: "$52,350",
    engine: "2.4L Hybrid",
    power: "340 hp",
    acceleration: "0-100 km/h in 5.7 sec",
    mpg: "6.5 L/100km city / 6.8 L/100km highway",
    description: "The Toyota Crown Platinum is a premium sedan that combines luxury with efficiency through its hybrid powertrain.",
    features: [
      "Hybrid powertrain",
      "Electronic On-Demand AWD",
      "Adaptive Variable Suspension",
      "12.3-inch touchscreen",
      "JBL premium audio",
      "Panoramic roof",
      "Heated and ventilated seats",
      "Advanced safety features"
    ]
  },
  {
    id: "toyota-crown-nightshade",
    name: "Crown Nightshade",
    brand: "Toyota",
    image: "/images/toyota/crown-nightshade.png",
    price: "$54,350",
    engine: "2.4L Hybrid",
    power: "340 hp",
    acceleration: "0-100 km/h in 5.7 sec",
    mpg: "6.5 L/100km city / 6.8 L/100km highway",
    description: "The Toyota Crown Nightshade offers a unique dark aesthetic while maintaining the same premium features and performance.",
    features: [
      "Hybrid powertrain",
      "Electronic On-Demand AWD",
      "Adaptive Variable Suspension",
      "12.3-inch touchscreen",
      "JBL premium audio",
      "Panoramic roof",
      "Heated and ventilated seats",
      "Advanced safety features",
      "Black chrome accents",
      "Black 21-inch wheels"
    ]
  },
  {
    id: "toyota-crown-limited",
    name: "Crown Limited",
    brand: "Toyota",
    image: "/images/toyota/crown-limited.png",
    price: "$48,350",
    engine: "2.4L Hybrid",
    power: "340 hp",
    acceleration: "0-100 km/h in 5.7 sec",
    mpg: "6.5 L/100km city / 6.8 L/100km highway",
    description: "The Toyota Crown Limited offers a balanced combination of luxury features and performance.",
    features: [
      "Hybrid powertrain",
      "Electronic On-Demand AWD",
      "Adaptive Variable Suspension",
      "12.3-inch touchscreen",
      "JBL premium audio",
      "Panoramic roof",
      "Heated and ventilated seats",
      "Advanced safety features"
    ]
  },
  {
    id: "toyota-crown-xle",
    name: "Crown XLE",
    brand: "Toyota",
    image: "/images/toyota/crown-xle.png",
    price: "$44,350",
    engine: "2.4L Hybrid",
    power: "340 hp",
    acceleration: "0-100 km/h in 5.7 sec",
    mpg: "6.5 L/100km city / 6.8 L/100km highway",
    description: "The Toyota Crown XLE offers a comfortable and efficient driving experience with premium features.",
    features: [
      "Hybrid powertrain",
      "Electronic On-Demand AWD",
      "Adaptive Variable Suspension",
      "12.3-inch touchscreen",
      "JBL premium audio",
      "Panoramic roof",
      "Heated and ventilated seats",
      "Advanced safety features"
    ]
  },
  {
    id: "toyota-corolla-le",
    name: "Corolla LE",
    brand: "Toyota",
    image: "/images/toyota/corolla-le.png",
    price: "$20,425",
    engine: "2.0L Inline-4",
    power: "169 hp",
    acceleration: "0-100 km/h in 8.2 sec",
    mpg: "8.1 L/100km city / 6.5 L/100km highway",
    description: "The Toyota Corolla LE is a reliable and efficient compact car that offers modern features and comfortable driving.",
    features: [
      "Front-wheel drive",
      "CVT transmission",
      "Toyota Safety Sense 3.0",
      "7-inch touchscreen",
      "Apple CarPlay and Android Auto",
      "Bluetooth connectivity",
      "LED headlights",
      "Smart key system"
    ]
  },
  {
    id: "toyota-corolla-hybrid-le",
    name: "Corolla Hybrid LE",
    brand: "Toyota",
    image: "/images/toyota/corolla-hybridle.png",
    price: "$23,050",
    engine: "1.8L Inline-4 Hybrid",
    power: "121 hp",
    acceleration: "0-100 km/h in 9.8 sec",
    mpg: "4.5 L/100km city / 4.2 L/100km highway",
    description: "The Toyota Corolla Hybrid LE combines efficiency with modern features for an eco-friendly driving experience.",
    features: [
      "Front-wheel drive",
      "CVT transmission",
      "Toyota Safety Sense 3.0",
      "7-inch touchscreen",
      "Apple CarPlay and Android Auto",
      "Bluetooth connectivity",
      "LED headlights",
      "Smart key system"
    ]
  },
  {
    id: "toyota-corolla-se",
    name: "Corolla SE",
    brand: "Toyota",
    image: "/images/toyota/corolla-se.png",
    price: "$22,425",
    engine: "2.0L Inline-4",
    power: "169 hp",
    acceleration: "0-100 km/h in 7.1 sec",
    mpg: "8.1 L/100km city / 6.5 L/100km highway",
    description: "The Toyota Corolla SE offers sporty styling and enhanced driving dynamics while maintaining efficiency.",
    features: [
      "Front-wheel drive",
      "CVT transmission",
      "Toyota Safety Sense 3.0",
      "7-inch touchscreen",
      "Apple CarPlay and Android Auto",
      "Bluetooth connectivity",
      "LED headlights",
      "Smart key system",
      "Sport-tuned suspension",
      "17-inch alloy wheels"
    ]
  },
  {
    id: "toyota-corolla-fx",
    name: "Corolla FX",
    brand: "Toyota",
    image: "/images/toyota/corolla-fx.png",
    price: "$22,425",
    engine: "2.0L Inline-4",
    power: "169 hp",
    acceleration: "0-100 km/h in 7.1 sec",
    mpg: "8.1 L/100km city / 6.5 L/100km highway",
    description: "The Toyota Corolla FX offers a unique design package with enhanced features and driving dynamics.",
    features: [
      "Front-wheel drive",
      "CVT transmission",
      "Toyota Safety Sense 3.0",
      "7-inch touchscreen",
      "Apple CarPlay and Android Auto",
      "Bluetooth connectivity",
      "LED headlights",
      "Smart key system",
      "Sport-tuned suspension",
      "17-inch alloy wheels"
    ]
  },
  {
    id: "toyota-corolla-xse",
    name: "Corolla XSE",
    brand: "Toyota",
    image: "/images/toyota/corolla-xse.png",
    price: "$24,425",
    engine: "2.0L Inline-4",
    power: "169 hp",
    acceleration: "0-100 km/h in 7.1 sec",
    mpg: "8.1 L/100km city / 6.5 L/100km highway",
    description: "The Toyota Corolla XSE offers premium features and sporty styling for an enhanced driving experience.",
    features: [
      "Front-wheel drive",
      "CVT transmission",
      "Toyota Safety Sense 3.0",
      "7-inch touchscreen",
      "Apple CarPlay and Android Auto",
      "Bluetooth connectivity",
      "LED headlights",
      "Smart key system",
      "Sport-tuned suspension",
      "18-inch alloy wheels",
      "Dual zone automatic climate control",
      "7-inch multi-information display"
    ]
  },
  {
    id: "toyota-corolla-hybrid-xle",
    name: "Corolla Hybrid XLE",
    brand: "Toyota",
    image: "/images/toyota/corolla-hybridxle.png",
    price: "$24,425",
    engine: "1.8L Inline-4 Hybrid",
    power: "121 hp",
    acceleration: "0-100 km/h in 9.8 sec",
    mpg: "4.5 L/100km city / 4.2 L/100km highway",
    description: "The Toyota Corolla Hybrid XLE combines premium features with exceptional fuel efficiency.",
    features: [
      "Front-wheel drive",
      "CVT transmission",
      "Toyota Safety Sense 3.0",
      "7-inch touchscreen",
      "Apple CarPlay and Android Auto",
      "Bluetooth connectivity",
      "LED headlights",
      "Smart key system",
      "Dual zone automatic climate control",
      "7-inch multi-information display"
    ]
  },
  {
    id: "toyota-corolla-hybrid-se",
    name: "Corolla Hybrid SE",
    brand: "Toyota",
    image: "/images/toyota/corolla-hybridse.png",
    price: "$24,425",
    engine: "1.8L Inline-4 Hybrid",
    power: "121 hp",
    acceleration: "0-100 km/h in 9.8 sec",
    mpg: "4.5 L/100km city / 4.2 L/100km highway",
    description: "The Toyota Corolla Hybrid SE combines sporty styling with exceptional fuel efficiency.",
    features: [
      "Front-wheel drive",
      "CVT transmission",
      "Toyota Safety Sense 3.0",
      "7-inch touchscreen",
      "Apple CarPlay and Android Auto",
      "Bluetooth connectivity",
      "LED headlights",
      "Smart key system",
      "Sport-tuned suspension",
      "17-inch alloy wheels"
    ]
  },

  // Mercedes-Benz Models
  {
    id: "mercedes-amg-gt",
    name: "Mercedes-AMG GT",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/mercedesamggt.jpg",
    price: "$115,000",
    engine: "4.0L V8 Biturbo",
    power: "469 hp",
    acceleration: "0-100 km/h in 3.9 sec",
    mpg: "13.8 L/100km city / 9.4 L/100km highway",
    description: "The Mercedes-AMG GT is a high-performance sports car that delivers exceptional power and precision.",
    features: [
      "Rear-wheel drive",
      "7-speed AMG SPEEDSHIFT DCT",
      "AMG RIDE CONTROL suspension",
      "AMG ceramic high-performance brakes",
      "AMG Track Pace",
      "Burmester surround sound",
      "AMG Performance seats",
      "AMG steering wheel"
    ]
  },
  {
    id: "mercedes-cle200amgline-cabriolet",
    name: "CLE 200 AMG Line Cabriolet",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinecabriolet.jpg",
    price: "$63,900",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "0-100 km/h in 6.2 sec",
    mpg: "9.4 L/100km city / 7.1 L/100km highway",
    description: "The Mercedes-Benz CLE Cabriolet offers open-top motoring with luxury and performance.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC"
    ]
  },
  {
    id: "mercedes-cle200amgline-coupe",
    name: "CLE 200 AMG Line Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinecoupe.jpg",
    price: "$56,400",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "0-100 km/h in 6.1 sec",
    mpg: "9.4 L/100km city / 7.1 L/100km highway",
    description: "The Mercedes-Benz CLE Coupe combines luxury with sporty performance.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC"
    ]
  },
  {
    id: "mercedes-cle200amgline-premium-cabriolet",
    name: "CLE 200 AMG Line Premium Cabriolet",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinepremiumcabriolet.jpg",
    price: "$68,500",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "0-100 km/h in 6.2 sec",
    mpg: "9.4 L/100km city / 7.1 L/100km highway",
    description: "The Mercedes-Benz CLE Premium Cabriolet offers enhanced luxury features with open-top motoring.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation"
    ]
  },
  {
    id: "mercedes-cle200amgline-premium-coupe",
    name: "CLE 200 AMG Line Premium Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinepremiumcoupe.jpg",
    price: "$61,000",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "0-100 km/h in 6.1 sec",
    mpg: "9.4 L/100km city / 7.1 L/100km highway",
    description: "The Mercedes-Benz CLE Premium Coupe offers enhanced luxury features with sporty performance.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation"
    ]
  },
  {
    id: "mercedes-cle200amgline-premiumplus-cabriolet",
    name: "CLE 200 AMG Line Premium Plus Cabriolet",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinepremiumpluscabriolet.jpg",
    price: "$71,500",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "0-100 km/h in 6.2 sec",
    mpg: "9.4 L/100km city / 7.1 L/100km highway",
    description: "The Mercedes-Benz CLE Premium Plus Cabriolet offers the ultimate luxury experience with open-top motoring.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation",
      "360-degree camera",
      "Active Parking Assist"
    ]
  },
  {
    id: "mercedes-cle200amgline-premiumplus-coupe",
    name: "CLE 200 AMG Line Premium Plus Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinepremiumpluscoupe.jpg",
    price: "$64,000",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "0-100 km/h in 6.1 sec",
    mpg: "9.4 L/100km city / 7.1 L/100km highway",
    description: "The Mercedes-Benz CLE Premium Plus Coupe offers the ultimate luxury experience with sporty performance.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation",
      "360-degree camera",
      "Active Parking Assist"
    ]
  },
  {
    id: "mercedes-cle200d-amgline-cabriolet",
    name: "CLE 200d AMG Line Cabriolet",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200damglinecabriolet.jpg",
    price: "$63,900",
    engine: "2.0L Inline-4 Turbo Diesel",
    power: "197 hp",
    acceleration: "0-100 km/h in 7.2 sec",
    mpg: "6.5 L/100km city / 5.2 L/100km highway",
    description: "The Mercedes-Benz CLE Diesel Cabriolet offers efficient performance with open-top motoring.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC"
    ]
  },
  {
    id: "mercedes-cle200d-amgline-coupe",
    name: "CLE 200d AMG Line Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200damglinecoupe.jpg",
    price: "$56,400",
    engine: "2.0L Inline-4 Turbo Diesel",
    power: "197 hp",
    acceleration: "0-100 km/h in 7.0 sec",
    mpg: "6.5 L/100km city / 5.2 L/100km highway",
    description: "The Mercedes-Benz CLE Diesel Coupe offers efficient performance with luxury comfort.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC"
    ]
  },
  {
    id: "mercedes-cle200d-amgline-premium-cabriolet",
    name: "CLE 200d AMG Line Premium Cabriolet",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200damglinepremiumcabriolet.jpg",
    price: "$68,500",
    engine: "2.0L Inline-4 Turbo Diesel",
    power: "197 hp",
    acceleration: "0-100 km/h in 7.2 sec",
    mpg: "6.5 L/100km city / 5.2 L/100km highway",
    description: "The Mercedes-Benz CLE Diesel Premium Cabriolet offers enhanced luxury features with efficient performance.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation"
    ]
  },
  {
    id: "mercedes-cle200d-amgline-premium-coupe",
    name: "CLE 200d AMG Line Premium Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200damglinepremiumcoupe.jpg",
    price: "$61,000",
    engine: "2.0L Inline-4 Turbo Diesel",
    power: "197 hp",
    acceleration: "0-100 km/h in 7.0 sec",
    mpg: "6.5 L/100km city / 5.2 L/100km highway",
    description: "The Mercedes-Benz CLE Diesel Premium Coupe offers enhanced luxury features with efficient performance.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation"
    ]
  },
  // {
  //   id: "mercedes-cle200d-amgline-premiumplus-cabriolet",
  //   name: "CLE 200d AMG Line Premium Plus Cabriolet",
  //   brand: "Mercedes-Benz",
  //   image: "/images/mercedesbenz/cle200damglinepremiumpluscabriolet.jpg",
  //   price: "$71,500",
  //   engine: "2.0L Inline-4 Turbo Diesel",
  //   power: "197 hp",
  //   acceleration: "0-100 km/h in 7.2 sec",
  //   mpg: "6.5 L/100km city / 5.2 L/100km highway",
  //   description: "The Mercedes-Benz CLE Diesel Premium Plus Cabriolet offers the ultimate luxury experience with efficient performance.",
  //   features: [
  //     "Rear-wheel drive",
  //     "9G-TRONIC transmission",
  //     "AMG Line package",
  //     "MBUX infotainment system",
  //     "Burmester sound system",
  //     "Panoramic sunroof",
  //     "AMG performance steering wheel",
  //     "Active Distance Assist DISTRONIC",
  //     "Head-up display",
  //     "Augmented reality navigation",
  //     "360-degree camera",
  //     "Active Parking Assist"
  //   ]
  // },
  {
    id: "mercedes-cle220d-amgline-premiumplus-cabriolet",
    name: "CLE 220d AMG Line Premium Plus Cabriolet",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle220damglinepremiumpluscabriolet.jpg",
    price: "$71,500",
    engine: "2.0L Inline-4 Turbo Diesel",
    power: "197 hp",
    acceleration: "0-100 km/h in 7.2 sec",
    mpg: "6.5 L/100km city / 5.2 L/100km highway",
    description: "The Mercedes-Benz CLE Diesel Premium Plus Cabriolet offers the ultimate luxury experience with efficient performance.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation",
      "360-degree camera",
      "Active Parking Assist"
    ]
  },
  {
    id: "mercedes-cle220d-amgline-premiumplus-coupe",
    name: "CLE 220d AMG Line Premium Plus Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle220damglinepremiumpluscoupe.jpg",
    price: "$64,000",
    engine: "2.0L Inline-4 Turbo Diesel",
    power: "197 hp",
    acceleration: "0-100 km/h in 7.0 sec",
    mpg: "6.5 L/100km city / 5.2 L/100km highway",
    description: "The Mercedes-Benz CLE Diesel Premium Plus Coupe offers the ultimate luxury experience with efficient performance.",
    features: [
      "Rear-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation",
      "360-degree camera",
      "Active Parking Assist"
    ]
  },
  {
    id: "mercedes-cle300-4matic-amgline-premium-coupe",
    name: "CLE 300 4MATIC AMG Line Premium Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle3004maticamglinepremiumcoupe.jpg",
    price: "$68,500",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "0-100 km/h in 6.1 sec",
    mpg: "9.4 L/100km city / 7.1 L/100km highway",
    description: "The Mercedes-Benz CLE 4MATIC Premium Coupe offers enhanced luxury features with all-wheel drive capability.",
    features: [
      "4MATIC all-wheel drive",
      "9G-TRONIC transmission",
      "AMG Line package",
      "MBUX infotainment system",
      "Burmester sound system",
      "Panoramic sunroof",
      "AMG performance steering wheel",
      "Active Distance Assist DISTRONIC",
      "Head-up display",
      "Augmented reality navigation"
    ]
  }
] 