export const brands = [
  {
    name: "BMW",
    slug: "bmw",
    logo: "/images/bmw-logo.svg",
    shortDescription: "The Ultimate Driving Machine",
    description:
      "BMW, or Bayerische Motoren Werke, is a German luxury automobile manufacturer known for its performance-oriented vehicles. Founded in 1916, BMW has established itself as a symbol of driving excellence, innovative technology, and premium quality.",
    headquarters: "Munich, Germany",
    founded: 1916,
    website: "https://www.bmw.com",
  },
  {
    name: "Audi",
    slug: "audi",
    logo: "/images/audi-logo.png",
    shortDescription: "Vorsprung durch Technik",
    description:
      "Audi is a German luxury automobile manufacturer that designs, engineers, produces, markets and distributes luxury vehicles. Founded in 1909, Audi has been a subsidiary of Volkswagen Group since 1966 and is known for its distinctive four-ring logo.",
    headquarters: "Ingolstadt, Germany",
    founded: 1909,
    website: "https://www.audi.com",
  },
  {
    name: "Toyota",
    slug: "toyota",
    logo: "/images/toyota-logo.svg",
    shortDescription: "Let's Go Places",
    description:
      "Toyota Motor Corporation is a Japanese multinational automotive manufacturer headquartered in Toyota City, Japan. Founded in 1937, Toyota is one of the largest automobile manufacturers in the world, producing more than 10 million vehicles per year.",
    headquarters: "Toyota City, Japan",
    founded: 1937,
    website: "https://www.toyota.com",
  },
  {
    name: "Mercedes-Benz",
    slug: "mercedes",
    logo: "/images/mers-logo.svg",
    shortDescription: "The Best or Nothing",
    description:
      "Mercedes-Benz is a German global automobile marque and a division of Daimler AG. The brand is known for luxury vehicles, buses, coaches, and trucks. The headquarters is in Stuttgart, Baden-Württemberg. The name first appeared in 1926 under Daimler-Benz.",
    headquarters: "Stuttgart, Germany",
    founded: 1926,
    website: "https://www.mercedes-benz.com",
  },
]

export const featuredCars = [
  {
    id: "bmw-m5",
    name: "BMW M5",
    brand: "BMW",
    image: "/cars/bmw/m5.jpg",
    price: "$103,500",
    engine: "4.4L V8 Twin-Turbo",
    power: "617 hp",
    acceleration: "0-60 mph in 3.2s",
    mpg: "15 city / 21 highway",
    description: "The BMW M5 is a high-performance variant of the BMW 5 Series executive car. Known for its exceptional blend of luxury and performance, the M5 features a powerful twin-turbocharged V8 engine, sophisticated all-wheel-drive system, and premium interior amenities.",
    features: [
      "M xDrive all-wheel-drive system",
      "8-speed M Steptronic transmission",
      "20-inch M light-alloy wheels",
      "M compound brakes",
      "Merino leather upholstery",
      "BMW Live Cockpit Professional",
      "Harman Kardon surround sound system",
      "Active M Differential"
    ]
  },
  {
    id: "bmw-x5",
    name: "BMW X5",
    brand: "BMW",
    image: "/cars/bmw/x5.jpg",
    price: "$61,600",
    engine: "3.0L Inline-6 Turbo",
    power: "335 hp",
    acceleration: "0-60 mph in 5.3s",
    mpg: "21 city / 26 highway",
    description: "The BMW X5 is a luxury midsize SUV that combines versatility, comfort, and performance. It offers a spacious interior, advanced technology features, and capable handling both on and off the road.",
    features: [
      "xDrive all-wheel-drive",
      "8-speed automatic transmission",
      "Live Cockpit Professional",
      "Panoramic moonroof",
      "Power tailgate",
      "Parking Assistant Plus",
      "Driving Assistant Professional",
      "Comfort Access keyless entry"
    ]
  },
  {
    id: "bmw-x7",
    name: "X7",
    brand: "BMW",
    image: "/images/bmw/bmwx7.jpg",
    price: "$77,850",
    engine: "3.0L Inline-6 Turbo",
    power: "375 hp",
    acceleration: "5.8 sec",
    mpg: "19/24",
    description:
      "The BMW X7 is a full-size luxury SUV that offers three rows of seating, premium amenities, and powerful performance. It's the largest SUV in BMW's lineup.",
    features: [
      "xDrive all-wheel drive",
      "8-speed automatic transmission",
      "Air suspension",
      "Panoramic Sky Lounge LED roof",
      "Executive package with glass controls",
    ],
  },
  {
    id: "bmw-8-coupe",
    name: "8 Series Coupe",
    brand: "BMW",
    image: "/images/bmw/bmwer8coupe.jpg",
    price: "$85,000",
    engine: "3.0L Inline-6 Turbo",
    power: "335 hp",
    acceleration: "4.7 sec",
    mpg: "23/30",
    description:
      "The BMW 8 Series Coupe is a luxury grand tourer that combines elegant styling with high-performance capabilities. It features a sleek design, premium interior, and advanced technology.",
    features: [
      "Rear-wheel drive or xDrive all-wheel drive",
      "8-speed automatic transmission",
      "Adaptive M suspension",
      "Harman Kardon surround sound system",
      "BMW Live Cockpit Professional",
    ],
  },

  // Audi Models
  {
    id: "audi-a5",
    name: "A5",
    brand: "Audi",
    image: "/images/audi/audia5.jpg",
    price: "$44,000",
    engine: "2.0L Inline-4 Turbo",
    power: "261 hp",
    acceleration: "5.3 sec",
    mpg: "24/31",
    description:
      "The Audi A5 is a series of compact executive coupe cars produced by the German automobile manufacturer Audi. It combines elegant styling with advanced technology and a refined driving experience.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Audi virtual cockpit",
      "Bang & Olufsen sound system",
      "Audi pre sense safety systems",
    ],
  },
  {
    id: "audi-q5",
    name: "Q5",
    brand: "Audi",
    image: "/images/audi/audiq5.jpg",
    price: "$43,500",
    engine: "2.0L Inline-4 Turbo",
    power: "261 hp",
    acceleration: "5.7 sec",
    mpg: "23/28",
    description:
      "The Audi Q5 is a compact luxury crossover SUV that offers a perfect balance of performance, comfort, and practicality. It features Audi's renowned quattro all-wheel drive system and premium interior appointments.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Panoramic sunroof",
      "Audi MMI touch response system",
      "Adaptive cruise control",
    ],
  },
  {
    id: "audi-etron-gt",
    name: "e-tron GT",
    brand: "Audi",
    image: "/images/audi/audietrongt.jpg",
    price: "$102,400",
    engine: "Dual Electric Motors",
    power: "522 hp",
    acceleration: "3.9 sec",
    mpg: "82 MPGe",
    description:
      "The Audi e-tron GT is an all-electric four-door coupe produced by Audi. It shares its platform with the Porsche Taycan and features dual electric motors and all-wheel drive.",
    features: [
      "quattro all-wheel drive",
      "2-speed transmission",
      "Adaptive air suspension",
      "800-volt electrical architecture",
      "93.4 kWh battery",
    ],
  },
  {
    id: "audi-r8",
    name: "R8",
    brand: "Audi",
    image: "/images/audi/audir8.jpg",
    price: "$142,700",
    engine: "5.2L V10",
    power: "562 hp",
    acceleration: "3.6 sec",
    mpg: "14/23",
    description:
      "The Audi R8 is a mid-engine, 2-seater sports car that serves as Audi's halo vehicle. It features a naturally aspirated V10 engine, quattro all-wheel drive, and race-inspired design.",
    features: [
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch transmission",
      "Carbon fiber and aluminum construction",
      "Virtual cockpit",
      "Magnetic ride suspension",
    ],
  },

  // Toyota Models
  {
    id: "toyota-supra",
    name: "GR Supra 3.0",
    brand: "Toyota",
    image: "/images/toyota/grsupra3.0.png",
    price: "$56,500",
    engine: "3.0L Inline-6 Turbo",
    power: "382 hp",
    acceleration: "3.9 sec",
    mpg: "22/30",
    description:
      "The Toyota GR Supra is a sports car and grand tourer manufactured by Toyota. The fifth generation of the Supra was produced by Toyota in collaboration with BMW.",
    features: [
      "Rear-wheel drive",
      "8-speed automatic transmission",
      "Adaptive Variable Sport suspension",
      "Active differential",
      "Brembo 4-piston calipers",
    ],
  },
  {
    id: "toyota-supra-premium",
    name: "GR Supra 3.0 Premium",
    brand: "Toyota",
    image: "/images/toyota/grsupra3.0-premium.png",
    price: "$58,500",
    engine: "3.0L Inline-6 Turbo",
    power: "382 hp",
    acceleration: "3.9 sec",
    mpg: "22/30",
    description:
      "The GR Supra 3.0 Premium adds luxury features and enhanced technology to the base model, offering a more refined driving experience.",
    features: [
      "Rear-wheel drive",
      "8-speed automatic transmission",
      "Adaptive Variable Sport suspension",
      "Active differential",
      "Brembo 4-piston calipers",
      "Premium leather-trimmed seats",
      "12-speaker JBL audio system",
      "Head-up display",
    ],
  },
  {
    id: "toyota-crown",
    name: "Crown",
    brand: "Toyota",
    image: "/images/toyota/crown-platinum.png",
    price: "$52,350",
    engine: "2.4L Turbo Hybrid",
    power: "340 hp",
    acceleration: "5.7 sec",
    mpg: "29/32",
    description:
      "The Toyota Crown is a premium sedan that combines luxury, performance, and advanced technology. It features a sophisticated hybrid powertrain and premium amenities.",
    features: [
      "Electronic On-Demand AWD",
      "6-speed automatic transmission",
      "Adaptive Variable Suspension",
      "12.3-inch touchscreen display",
      "11-speaker JBL audio system",
      "Panoramic roof",
      "Heated and ventilated seats",
    ],
  },
  {
    id: "toyota-crown-nightshade",
    name: "Crown Nightshade",
    brand: "Toyota",
    image: "/images/toyota/crown-nightshade.png",
    price: "$54,350",
    engine: "2.4L Turbo Hybrid",
    power: "340 hp",
    acceleration: "5.7 sec",
    mpg: "29/32",
    description:
      "The Crown Nightshade edition adds distinctive styling elements and exclusive features to the standard Crown, creating a more unique and premium experience.",
    features: [
      "Electronic On-Demand AWD",
      "6-speed automatic transmission",
      "Adaptive Variable Suspension",
      "12.3-inch touchscreen display",
      "11-speaker JBL audio system",
      "Panoramic roof",
      "Heated and ventilated seats",
      "Black chrome accents",
      "Black 21-inch wheels",
    ],
  },
  {
    id: "toyota-corolla",
    name: "Corolla",
    brand: "Toyota",
    image: "/images/toyota/corolla-le.png",
    price: "$20,425",
    engine: "1.8L Inline-4",
    power: "139 hp",
    acceleration: "8.5 sec",
    mpg: "31/40",
    description:
      "The Toyota Corolla is a line of compact cars manufactured by Toyota. It has become one of the best-selling cars worldwide since its introduction in 1966.",
    features: [
      "Front-wheel drive",
      "CVT automatic transmission",
      "Toyota Safety Sense 2.0",
      "Apple CarPlay and Android Auto",
      "LED headlights",
    ],
  },
  {
    id: "toyota-corolla-hybrid",
    name: "Corolla Hybrid",
    brand: "Toyota",
    image: "/images/toyota/corolla-hybridle.png",
    price: "$23,050",
    engine: "1.8L Inline-4 Hybrid",
    power: "121 hp (combined)",
    acceleration: "9.8 sec",
    mpg: "53/46",
    description:
      "The Toyota Corolla Hybrid combines the practicality of the Corolla with the efficiency of Toyota's hybrid technology, offering excellent fuel economy without compromising on comfort.",
    features: [
      "Front-wheel drive",
      "Electronically controlled CVT",
      "Lithium-ion battery",
      "Toyota Safety Sense 2.0",
      "7-inch multi-information display",
      "Dual zone automatic climate control",
    ],
  },
  {
    id: "toyota-corolla-se",
    name: "Corolla SE",
    brand: "Toyota",
    image: "/images/toyota/corolla-se.png",
    price: "$22,425",
    engine: "2.0L Inline-4",
    power: "169 hp",
    acceleration: "7.1 sec",
    mpg: "29/36",
    description:
      "The Corolla SE adds sporty styling and enhanced performance to the standard Corolla, making it more engaging to drive while maintaining practicality.",
    features: [
      "Front-wheel drive",
      "CVT automatic transmission",
      "Toyota Safety Sense 2.0",
      "Apple CarPlay and Android Auto",
      "LED headlights",
      "Sport-tuned suspension",
      "17-inch alloy wheels",
      "Sport seats",
    ],
  },
  {
    id: "toyota-corolla-xse",
    name: "Corolla XSE",
    brand: "Toyota",
    image: "/images/toyota/corolla-xse.png",
    price: "$24,425",
    engine: "2.0L Inline-4",
    power: "169 hp",
    acceleration: "7.1 sec",
    mpg: "29/36",
    description:
      "The Corolla XSE represents the top of the line for the standard Corolla, offering premium features and sporty styling in a practical package.",
    features: [
      "Front-wheel drive",
      "CVT automatic transmission",
      "Toyota Safety Sense 2.0",
      "Apple CarPlay and Android Auto",
      "LED headlights",
      "Sport-tuned suspension",
      "18-inch alloy wheels",
      "Sport seats",
      "Dual zone automatic climate control",
      "7-inch multi-information display",
    ],
  },

  // Mercedes Models
  {
    id: "mercedes-amg-gt",
    name: "AMG GT",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/mercedesamggt.jpg",
    price: "$118,600",
    engine: "4.0L V8 Biturbo",
    power: "523 hp",
    acceleration: "3.7 sec",
    mpg: "15/20",
    description:
      "The Mercedes-AMG GT is a grand tourer produced by Mercedes-AMG. It combines breathtaking performance with luxurious comfort and striking design.",
    features: [
      "AMG SPEEDSHIFT DCT 7-speed transmission",
      "AMG RIDE CONTROL suspension",
      "AMG high-performance composite braking system",
      "AMG DYNAMIC SELECT",
      "Burmester surround sound system",
    ],
  },
  {
    id: "mercedes-cle-coupe",
    name: "CLE Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinecoupe.jpg",
    price: "$56,400",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "6.1 sec",
    mpg: "23/31",
    description:
      "The Mercedes-Benz CLE Coupe is a luxury two-door coupe that combines elegant styling with advanced technology and a refined driving experience.",
    features: [
      "9G-TRONIC 9-speed automatic transmission",
      "DYNAMIC SELECT",
      "LED Intelligent Light System",
      "12.3-inch digital instrument cluster",
      "11.9-inch central touchscreen display",
    ],
  },
  {
    id: "mercedes-cle-cabriolet",
    name: "CLE Cabriolet",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinecabriolet.jpg",
    price: "$63,900",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "6.2 sec",
    mpg: "22/30",
    description:
      "The Mercedes-Benz CLE Cabriolet is a luxury convertible that offers open-air driving pleasure with the refinement and technology expected from Mercedes-Benz.",
    features: [
      "9G-TRONIC 9-speed automatic transmission",
      "AIRCAP wind deflector",
      "AIRSCARF neck-level heating",
      "Acoustic soft top",
      "MBUX multimedia system",
    ],
  },
  {
    id: "mercedes-cle-premium",
    name: "CLE Premium Plus Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200damglinepremiumpluscoupe.jpg",
    price: "$68,500",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    acceleration: "6.1 sec",
    mpg: "23/31",
    description:
      "The Mercedes-Benz CLE Premium Plus Coupe offers additional luxury features and technology upgrades over the standard CLE Coupe, providing an even more refined driving experience.",
    features: [
      "Burmester 3D surround sound system",
      "Head-up display",
      "Augmented reality navigation",
      "Active Parking Assist",
      "AMG Line exterior and interior",
    ],
  },
]

export const carSpecs = {
  "bmw-m5": {
    performance: {
      "Engine Type": "4.4L V8 Twin-Turbo",
      "Horsepower": "617 hp @ 6,000 rpm",
      "Torque": "553 lb-ft @ 1,800-5,860 rpm",
      "Transmission": "8-speed M Steptronic",
      "Drivetrain": "M xDrive all-wheel-drive",
      "0-60 mph": "3.2 seconds",
      "Top Speed": "155 mph (limited)"
    },
    dimensions: {
      "Length": "196.4 inches",
      "Width": "74.9 inches",
      "Height": "58.2 inches",
      "Wheelbase": "117.4 inches",
      "Curb Weight": "4,345 lbs",
      "Cargo Volume": "14.0 cubic feet"
    },
    fuelEconomy: {
      "City": "15 mpg",
      "Highway": "21 mpg",
      "Combined": "17 mpg",
      "Fuel Tank": "20.1 gallons"
    }
  },
  "bmw-x5": {
    performance: {
      "Engine Type": "3.0L Inline-6 Turbo",
      "Horsepower": "335 hp @ 5,500 rpm",
      "Torque": "331 lb-ft @ 1,500-5,200 rpm",
      "Transmission": "8-speed automatic",
      "Drivetrain": "xDrive all-wheel-drive",
      "0-60 mph": "5.3 seconds",
      "Top Speed": "150 mph (limited)"
    },
    dimensions: {
      "Length": "194.3 inches",
      "Width": "78.9 inches",
      "Height": "69.0 inches",
      "Wheelbase": "117.1 inches",
      "Curb Weight": "4,863 lbs",
      "Cargo Volume": "33.9 cubic feet"
    },
    fuelEconomy: {
      "City": "21 mpg",
      "Highway": "26 mpg",
      "Combined": "23 mpg",
      "Fuel Tank": "21.9 gallons"
    }
  },
  "bmw-x3": {
    performance: {
      Engine: "2.0L Inline-4 Turbo",
      Power: "248 hp @ 5,200-6,500 rpm",
      Torque: "258 lb-ft @ 1,450-4,800 rpm",
      Transmission: "8-speed automatic",
      Drivetrain: "xDrive all-wheel drive",
      "0-60 mph": "6.0 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "23 city / 30 highway",
    },
    dimensions: {
      Length: "185.9 inches",
      Width: "74.4 inches",
      Height: "66.0 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "4,055 lbs",
      "Cargo Volume": "28.7 cubic feet",
    },
    features: {
      Exterior: [
        "LED headlights",
        "18-inch aluminum wheels",
        "Power tailgate",
        "Roof rails",
        "Chrome window trim",
      ],
      Interior: [
        "Sensatec upholstery",
        "10.25-inch touchscreen display",
        "12.3-inch digital instrument cluster",
        "10-speaker audio system",
        "Dual zone automatic climate control",
      ],
      Safety: [
        "Active Driving Assistant",
        "Frontal collision warning",
        "Lane departure warning",
        "Active blind spot detection",
        "Parking Assistant",
      ],
    },
  },
  "bmw-x3m": {
    performance: {
      Engine: "3.0L Inline-6 Twin-Turbo",
      Power: "473 hp @ 6,250 rpm",
      Torque: "442 lb-ft @ 2,600-5,250 rpm",
      Transmission: "8-speed M Steptronic",
      Drivetrain: "M xDrive all-wheel drive",
      "0-60 mph": "4.1 seconds",
      "Top Speed": "155 mph (limited)",
      "Fuel Economy": "14 city / 19 highway",
    },
    dimensions: {
      Length: "185.9 inches",
      Width: "74.4 inches",
      Height: "66.0 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "4,275 lbs",
      "Cargo Volume": "28.7 cubic feet",
    },
    features: {
      Exterior: [
        "M-specific front bumper",
        "M rear spoiler",
        "M-specific side mirrors",
        "Quad exhaust tips",
        "20-inch M double-spoke wheels",
      ],
      Interior: [
        "M Sport seats",
        "M leather steering wheel",
        "12.3-inch digital instrument cluster",
        "12.3-inch central information display",
        "16-speaker Harman Kardon surround sound system",
      ],
      Safety: [
        "Active Driving Assistant",
        "Frontal collision warning",
        "Lane departure warning",
        "Active blind spot detection",
        "Surround view camera system",
      ],
    },
  },
  "bmw-x5m": {
    performance: {
      Engine: "4.4L V8 Twin-Turbo",
      Power: "600 hp @ 6,000 rpm",
      Torque: "553 lb-ft @ 1,800-5,860 rpm",
      Transmission: "8-speed M Steptronic",
      Drivetrain: "M xDrive all-wheel drive",
      "0-60 mph": "3.8 seconds",
      "Top Speed": "155 mph (limited)",
      "Fuel Economy": "13 city / 18 highway",
    },
    dimensions: {
      Length: "194.3 inches",
      Width: "78.9 inches",
      Height: "69.1 inches",
      Wheelbase: "117.1 inches",
      "Curb Weight": "5,290 lbs",
      "Cargo Volume": "33.9 cubic feet",
    },
    features: {
      Exterior: [
        "M-specific front bumper",
        "M rear spoiler",
        "M-specific side mirrors",
        "Quad exhaust tips",
        "21-inch M double-spoke wheels",
      ],
      Interior: [
        "M Sport seats",
        "M leather steering wheel",
        "12.3-inch digital instrument cluster",
        "12.3-inch central information display",
        "16-speaker Harman Kardon surround sound system",
      ],
      Safety: [
        "Active Driving Assistant",
        "Frontal collision warning",
        "Lane departure warning",
        "Active blind spot detection",
        "Surround view camera system",
      ],
    },
  },
  "bmw-x7": {
    performance: {
      Engine: "3.0L Inline-6 Turbo",
      Power: "375 hp @ 5,500-6,500 rpm",
      Torque: "383 lb-ft @ 1,600-5,000 rpm",
      Transmission: "8-speed automatic",
      Drivetrain: "xDrive all-wheel drive",
      "0-60 mph": "5.8 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "19 city / 24 highway",
    },
    dimensions: {
      Length: "203.3 inches",
      Width: "78.7 inches",
      Height: "71.1 inches",
      Wheelbase: "122.2 inches",
      "Curb Weight": "5,370 lbs",
      "Cargo Volume": "48.6 cubic feet",
    },
    features: {
      Exterior: [
        "LED headlights",
        "21-inch aluminum wheels",
        "Power tailgate",
        "Panoramic Sky Lounge LED roof",
        "Chrome window trim",
      ],
      Interior: [
        "Sensatec upholstery",
        "12.3-inch touchscreen display",
        "12.3-inch digital instrument cluster",
        "16-speaker Harman Kardon surround sound system",
        "Tri-zone automatic climate control",
      ],
      Safety: [
        "Active Driving Assistant",
        "Frontal collision warning",
        "Lane departure warning",
        "Active blind spot detection",
        "Parking Assistant",
      ],
    },
  },
  "bmw-er8coupe": {
    performance: {
      Engine: "3.0L Inline-6 Turbo",
      Power: "335 hp @ 5,500-6,500 rpm",
      Torque: "368 lb-ft @ 1,600-5,000 rpm",
      Transmission: "8-speed automatic",
      Drivetrain: "xDrive all-wheel drive",
      "0-60 mph": "4.7 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "23 city / 30 highway",
    },
    dimensions: {
      Length: "191.2 inches",
      Width: "74.9 inches",
      Height: "53.0 inches",
      Wheelbase: "111.1 inches",
      "Curb Weight": "4,478 lbs",
      "Cargo Volume": "15.0 cubic feet",
    },
    features: {
      Exterior: [
        "LED headlights",
        "19-inch aluminum wheels",
        "Power tailgate",
        "Panoramic moonroof",
        "Chrome window trim",
      ],
      Interior: [
        "Sensatec upholstery",
        "12.3-inch touchscreen display",
        "12.3-inch digital instrument cluster",
        "16-speaker Harman Kardon surround sound system",
        "Dual zone automatic climate control",
      ],
      Safety: [
        "Active Driving Assistant",
        "Frontal collision warning",
        "Lane departure warning",
        "Active blind spot detection",
        "Parking Assistant",
      ],
    },
  },
  "audi-r8": {
    performance: {
      Engine: "5.2L V10",
      Power: "562 hp @ 8,100 rpm",
      Torque: "406 lb-ft @ 6,300 rpm",
      Transmission: "7-speed S tronic dual-clutch",
      Drivetrain: "quattro all-wheel drive",
      "0-60 mph": "3.6 seconds",
      "Top Speed": "201 mph",
      "Fuel Economy": "14 city / 23 highway",
    },
    dimensions: {
      Length: "174.4 inches",
      Width: "76.4 inches",
      Height: "48.7 inches",
      Wheelbase: "104.3 inches",
      "Curb Weight": "3,627 lbs",
      "Cargo Volume": "8.0 cubic feet",
    },
    features: {
      Exterior: [
        "Full LED headlights with Audi laser light",
        "Carbon fiber side blades",
        "Fixed rear spoiler",
        "Dual oval exhaust outlets",
        "20-inch 5-V-spoke design forged wheels",
      ],
      Interior: [
        "Fine Nappa leather seats with diamond stitching",
        "Flat-bottom steering wheel with multifunction controls",
        "12.3-inch Audi virtual cockpit",
        "MMI Navigation plus with MMI touch",
        "Bang & Olufsen sound system with 13 speakers",
      ],
      Safety: [
        "Audi pre sense basic and front",
        "Parking system plus with rearview camera",
        "Tire pressure monitoring system",
        "Electronic stability control",
        "Front knee airbags",
      ],
    },
  },
  "toyota-supra": {
    performance: {
      Engine: "3.0L Inline-6 Turbo",
      Power: "382 hp @ 5,800-6,500 rpm",
      Torque: "368 lb-ft @ 1,800-5,000 rpm",
      Transmission: "8-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "3.9 seconds",
      "Top Speed": "155 mph (limited)",
      "Fuel Economy": "22 city / 30 highway",
    },
    dimensions: {
      Length: "172.5 inches",
      Width: "73.0 inches",
      Height: "50.9 inches",
      Wheelbase: "97.2 inches",
      "Curb Weight": "3,400 lbs",
      "Cargo Volume": "10.2 cubic feet",
    },
    features: {
      Exterior: [
        "Double-bubble roof design",
        "Six-lens LED headlights",
        "Integrated rear spoiler",
        "Dual exhaust outlets",
        "19-inch forged aluminum wheels",
      ],
      Interior: [
        "Sport seats with Alcantara and leather trim",
        "Carbon fiber interior trim",
        "8.8-inch touchscreen display",
        "Digital instrument cluster",
        "JBL 12-speaker sound system",
      ],
      Safety: [
        "Pre-collision system with pedestrian detection",
        "Lane departure warning with steering assist",
        "Automatic high beams",
        "Dynamic radar cruise control",
        "Blind spot monitoring",
      ],
    },
  },
  "mercedes-amg-gt": {
    performance: {
      Engine: "4.0L V8 Biturbo",
      Power: "523 hp @ 5,500-6,750 rpm",
      Torque: "494 lb-ft @ 2,100-5,250 rpm",
      Transmission: "AMG SPEEDSHIFT DCT 7-speed",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "3.7 seconds",
      "Top Speed": "193 mph",
      "Fuel Economy": "15 city / 20 highway",
    },
    dimensions: {
      Length: "179.0 inches",
      Width: "76.3 inches",
      Height: "50.7 inches",
      Wheelbase: "103.5 inches",
      "Curb Weight": "3,616 lbs",
      "Cargo Volume": "10.1 cubic feet",
    },
    features: {
      Exterior: [
        "AMG-specific grille",
        "LED high-performance headlamps",
        "Active rear spoiler",
        "Quad exhaust tips",
        "19/20-inch AMG 10-spoke wheels",
      ],
      Interior: [
        "AMG Performance seats",
        "Nappa leather upholstery",
        "AMG Performance steering wheel",
        "12.3-inch digital instrument cluster",
        "10.25-inch multimedia display",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
      ],
    },
  },
  "mercedes-cle200amglinecoupe": {
    performance: {
      Engine: "2.0L Inline-4 Turbo",
      Power: "255 hp @ 5,800-6,100 rpm",
      Torque: "295 lb-ft @ 2,000-3,200 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "6.1 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "23 city / 31 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,748 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "18-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
      ],
      Interior: [
        "MB-Tex upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "10-speaker audio system",
        "Dual zone automatic climate control",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
      ],
    },
  },
  "mercedes-cle200amglinecabriolet": {
    performance: {
      Engine: "2.0L Inline-4 Turbo",
      Power: "255 hp @ 5,800-6,100 rpm",
      Torque: "295 lb-ft @ 2,000-3,200 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "6.2 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "22 city / 30 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,902 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "18-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
        "Acoustic soft top",
      ],
      Interior: [
        "MB-Tex upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "10-speaker audio system",
        "Dual zone automatic climate control",
        "AIRCAP wind deflector",
        "AIRSCARF neck-level heating",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
        "Active Parking Assist",
      ],
    },
  },
  "mercedes-cle200amglinepremiumcoupe": {
    performance: {
      Engine: "2.0L Inline-4 Turbo",
      Power: "255 hp @ 5,800-6,100 rpm",
      Torque: "295 lb-ft @ 2,000-3,200 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "6.1 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "23 city / 31 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,748 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "19-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
        "Panoramic sunroof",
      ],
      Interior: [
        "Leather upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "13-speaker Burmester sound system",
        "Dual zone automatic climate control",
        "Head-up display",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
        "Active Parking Assist",
      ],
    },
  },
  "mercedes-cle200amglinepremiumpluscoupe": {
    performance: {
      Engine: "2.0L Inline-4 Turbo",
      Power: "255 hp @ 5,800-6,100 rpm",
      Torque: "295 lb-ft @ 2,000-3,200 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "6.1 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "23 city / 31 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,748 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "19-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
        "Panoramic sunroof",
      ],
      Interior: [
        "Leather upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "13-speaker Burmester sound system",
        "Dual zone automatic climate control",
        "Head-up display",
        "Augmented reality navigation",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
        "Active Parking Assist",
        "360-degree camera",
      ],
    },
  },
  "mercedes-cle200amglinepremiumcabriolet": {
    performance: {
      Engine: "2.0L Inline-4 Turbo",
      Power: "255 hp @ 5,800-6,100 rpm",
      Torque: "295 lb-ft @ 2,000-3,200 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "6.2 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "22 city / 30 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,902 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "19-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
        "Acoustic soft top",
      ],
      Interior: [
        "Leather upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "13-speaker Burmester sound system",
        "Dual zone automatic climate control",
        "Head-up display",
        "AIRCAP wind deflector",
        "AIRSCARF neck-level heating",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
        "Active Parking Assist",
      ],
    },
  },
  "mercedes-cle200damglinecoupe": {
    performance: {
      Engine: "2.0L Inline-4 Turbo Diesel",
      Power: "197 hp @ 5,800-6,100 rpm",
      Torque: "320 lb-ft @ 1,800-2,800 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "7.0 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "27 city / 35 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,748 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "18-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
      ],
      Interior: [
        "MB-Tex upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "10-speaker audio system",
        "Dual zone automatic climate control",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
      ],
    },
  },
  "mercedes-cle200damglinepremiumcoupe": {
    performance: {
      Engine: "2.0L Inline-4 Turbo Diesel",
      Power: "197 hp @ 5,800-6,100 rpm",
      Torque: "320 lb-ft @ 1,800-2,800 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "7.0 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "27 city / 35 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,748 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "19-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
        "Panoramic sunroof",
      ],
      Interior: [
        "Leather upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "13-speaker Burmester sound system",
        "Dual zone automatic climate control",
        "Head-up display",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
        "Active Parking Assist",
      ],
    },
  },
  "mercedes-cle220damglinepremiumpluscoupe": {
    performance: {
      Engine: "2.0L Inline-4 Turbo Diesel",
      Power: "197 hp @ 5,800-6,100 rpm",
      Torque: "320 lb-ft @ 1,800-2,800 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "7.0 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "27 city / 35 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,748 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "19-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
        "Panoramic sunroof",
      ],
      Interior: [
        "Leather upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "13-speaker Burmester sound system",
        "Dual zone automatic climate control",
        "Head-up display",
        "Augmented reality navigation",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
        "Active Parking Assist",
        "360-degree camera",
      ],
    },
  },
  "mercedes-cle220damglinepremiumcabriolet": {
    performance: {
      Engine: "2.0L Inline-4 Turbo Diesel",
      Power: "197 hp @ 5,800-6,100 rpm",
      Torque: "320 lb-ft @ 1,800-2,800 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "Rear-wheel drive",
      "0-60 mph": "7.2 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "26 city / 34 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,902 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "19-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
        "Acoustic soft top",
      ],
      Interior: [
        "Leather upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "13-speaker Burmester sound system",
        "Dual zone automatic climate control",
        "Head-up display",
        "AIRCAP wind deflector",
        "AIRSCARF neck-level heating",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
        "Active Parking Assist",
      ],
    },
  },
  "mercedes-cle3004maticamglinepremiumcoupe": {
    performance: {
      Engine: "2.0L Inline-4 Turbo",
      Power: "255 hp @ 5,800-6,100 rpm",
      Torque: "295 lb-ft @ 2,000-3,200 rpm",
      Transmission: "9G-TRONIC 9-speed automatic",
      Drivetrain: "4MATIC all-wheel drive",
      "0-60 mph": "6.1 seconds",
      "Top Speed": "130 mph",
      "Fuel Economy": "22 city / 29 highway",
    },
    dimensions: {
      Length: "184.7 inches",
      Width: "72.9 inches",
      Height: "54.8 inches",
      Wheelbase: "112.8 inches",
      "Curb Weight": "3,748 lbs",
      "Cargo Volume": "13.1 cubic feet",
    },
    features: {
      Exterior: [
        "LED Intelligent Light System",
        "19-inch AMG 5-spoke wheels",
        "AMG Line body styling",
        "Chrome window trim",
        "Dual exhaust outlets",
        "Panoramic sunroof",
      ],
      Interior: [
        "Leather upholstery",
        "11.9-inch central touchscreen",
        "12.3-inch digital instrument cluster",
        "13-speaker Burmester sound system",
        "Dual zone automatic climate control",
        "Head-up display",
      ],
      Safety: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
        "Rearview camera",
        "Adaptive highbeam assist",
        "Active Parking Assist",
      ],
    },
  },
}

export const compareData = [
  {
    id: "bmw-m5",
    name: "M5",
    brand: "BMW",
    image: "/images/bmw/bmwm5.jpg",
    price: "$103,500",
    engine: "4.4L V8 Twin-Turbo",
    power: "617 hp",
    torque: "553 lb-ft",
    acceleration: "3.1 sec",
    topSpeed: "155 mph",
    mpg: "15/21",
    transmission: "8-speed Automatic",
    drivetrain: "AWD",
    weight: "4,345 lbs",
  },
  {
    id: "audi-r8",
    name: "R8",
    brand: "Audi",
    image: "/images/audi/audir8.jpg",
    price: "$142,700",
    engine: "5.2L V10",
    power: "562 hp",
    torque: "406 lb-ft",
    acceleration: "3.6 sec",
    topSpeed: "201 mph",
    mpg: "14/23",
    transmission: "7-speed Dual-Clutch",
    drivetrain: "AWD",
    weight: "3,627 lbs",
  },
  {
    id: "toyota-supra",
    name: "GR Supra",
    brand: "Toyota",
    image: "/images/toyota/grsupra.jpg",
    price: "$55,500",
    engine: "3.0L Inline-6 Turbo",
    power: "382 hp",
    torque: "368 lb-ft",
    acceleration: "3.9 sec",
    topSpeed: "155 mph",
    mpg: "22/30",
    transmission: "8-speed Automatic",
    drivetrain: "RWD",
    weight: "3,400 lbs",
  },
  {
    id: "mercedes-amg-gt",
    name: "AMG GT",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/mercedesamggt.jpg",
    price: "$118,600",
    engine: "4.0L V8 Biturbo",
    power: "523 hp",
    torque: "494 lb-ft",
    acceleration: "3.7 sec",
    topSpeed: "193 mph",
    mpg: "15/20",
    transmission: "7-speed Dual-Clutch",
    drivetrain: "RWD",
    weight: "3,616 lbs",
  },
  {
    id: "bmw-x5",
    name: "X5",
    brand: "BMW",
    image: "/images/bmw/bmwx5.jpg",
    price: "$61,600",
    engine: "3.0L Inline-6 Turbo",
    power: "335 hp",
    torque: "331 lb-ft",
    acceleration: "5.3 sec",
    topSpeed: "150 mph",
    mpg: "21/26",
    transmission: "8-speed Automatic",
    drivetrain: "AWD",
    weight: "4,840 lbs",
  },
  {
    id: "audi-q5",
    name: "Q5",
    brand: "Audi",
    image: "/images/audi/audiq5.jpg",
    price: "$43,500",
    engine: "2.0L Inline-4 Turbo",
    power: "261 hp",
    torque: "273 lb-ft",
    acceleration: "5.7 sec",
    topSpeed: "130 mph",
    mpg: "23/28",
    transmission: "7-speed Dual-Clutch",
    drivetrain: "AWD",
    weight: "4,079 lbs",
  },
  {
    id: "toyota-corolla",
    name: "Corolla",
    brand: "Toyota",
    image: "/images/toyota/corolla.jpg",
    price: "$20,425",
    engine: "2.0L Inline-4",
    power: "169 hp",
    torque: "151 lb-ft",
    acceleration: "7.1 sec",
    topSpeed: "118 mph",
    mpg: "29/36",
    transmission: "CVT Automatic",
    drivetrain: "FWD",
    weight: "3,150 lbs",
  },
  {
    id: "mercedes-cle-coupe",
    name: "CLE Coupe",
    brand: "Mercedes-Benz",
    image: "/images/mercedesbenz/cle200amglinecoupe.jpg",
    price: "$56,400",
    engine: "2.0L Inline-4 Turbo",
    power: "255 hp",
    torque: "295 lb-ft",
    acceleration: "6.1 sec",
    topSpeed: "130 mph",
    mpg: "23/31",
    transmission: "9-speed Automatic",
    drivetrain: "RWD",
    weight: "3,748 lbs",
  },
]

export const images = {
  // Brand logos and backgrounds
  logos: {
    bmw: "/images/bmw-logo.svg",
    audi: "/images/audi-logo.png",
    toyota: "/images/toyota-logo.svg",
    mercedes: "/images/mers-logo.svg",
  },
  backgrounds: {
    bmw: "/images/bmw-bg.jpg",
    audi: "/images/audi-bg.jpg",
    toyota: "/images/toyota_bg.webp",
    mercedes: "/images/mercedesbenz.jpg",
  },
  // BMW images
  bmw: {
    "m5": "/images/bmw/bmwm5.jpg",
    "x3": "/images/bmw/bmwx3.jpg",
    "x3m": "/images/bmw/bmwx3m.jpg",
    "x4": "/images/bmw/bmwx4.jpg",
    "x4m": "/images/bmw/bmwx4m.jpg",
    "x5": "/images/bmw/bmwx5.jpg",
    "x5m": "/images/bmw/bmwx5m.jpg",
    "x6": "/images/bmw/bmwx6.jpg",
    "x6m": "/images/bmw/bmwx6m.jpg",
    "x7": "/images/bmw/bmwx7.jpg",
    "er2": "/images/bmw/bmwer2.jpg",
    "er3": "/images/bmw/bmwer3.jpg",
    "er3m": "/images/bmw/bmwer3m.jpg",
    "er4": "/images/bmw/bmwer4.jpg",
    "er4m": "/images/bmw/bmwer4m.jpg",
    "er4cupe": "/images/bmw/bmwer4cupe.jpg",
    "er7": "/images/bmw/bmwer7.jpg",
    "er7m": "/images/bmw/bmwer7m.jpg",
    "er8": "/images/bmw/bmwer8.jpg",
    "er8m": "/images/bmw/bmwer8m.jpg",
    "er8carbio": "/images/bmw/bmwer8carbio.jpg"
  },
  // Audi images
  audi: {
    "a3": "/images/audi/audia3.jpg",
    "a4": "/images/audi/audia4.jpg",
    "a5": "/images/audi/audia5.jpg",
    "a6": "/images/audi/audia6.jpg",
    "a8": "/images/audi/audia8.jpg",
    "q3": "/images/audi/audiq3.jpg",
    "q4etron": "/images/audi/audiq4etron.jpg",
    "q5": "/images/audi/audiq5.jpg",
    "q8": "/images/audi/audiq8.jpg",
    "q8etron": "/images/audi/audiq8etron.jpg",
    "tt": "/images/audi/auditt.jpg",
    "etrongt": "/images/audi/audietrongt.jpg",
    "r8": "/images/audi/audir8.jpg",
    "rs7": "/images/audi/audirs7.jpg",
    "allnewa5": "/images/audi/allnewa5.jpg"
  },
  // Mercedes-Benz images
  mercedes: {
    "amggt": "/images/mercedesbenz/mercedesamggt.jpg",
    "cle200amglinecoupe": "/images/mercedesbenz/cle200amglinecoupe.jpg",
    "cle200amglinecabriolet": "/images/mercedesbenz/cle200amglinecabriolet.jpg",
    "cle200amglinepremiumcoupe": "/images/mercedesbenz/cle200amglinepremiumcoupe.jpg",
    "cle200amglinepremiumpluscoupe": "/images/mercedesbenz/cle200amglinepremiumpluscoupe.jpg",
    "cle200amglinepremiumcabriolet": "/images/mercedesbenz/cle200amglinepremiumcabriolet.jpg",
    "cle200damglinecoupe": "/images/mercedesbenz/cle200damglinecoupe.jpg",
    "cle200damglinepremiumcoupe": "/images/mercedesbenz/cle200damglinepremiumcoupe.jpg",
    "cle220damglinepremiumpluscoupe": "/images/mercedesbenz/cle220damglinepremiumpluscoupe.jpg",
    "cle220damglinepremiumcabriolet": "/images/mercedesbenz/cle220damglinepremiumcabriolet.jpg",
    "cle3004maticamglinepremiumcoupe": "/images/mercedesbenz/cle3004maticamglinepremiumcoupe.jpg"
  },
  // Toyota images
  toyota: {
    "grsupra3.0": "/images/toyota/grsupra3.0.png",
    "grsupra3.0-premium": "/images/toyota/grsupra3.0-premium.png",
    "crown-platinum": "/images/toyota/crown-platinum.png",
    "crown-nightshade": "/images/toyota/crown-nightshade.png",
    "crown-limited": "/images/toyota/crown-limited.png",
    "crown-xle": "/images/toyota/crown-xle.png",
    "corolla-le": "/images/toyota/corolla-le.png",
    "corolla-hybridle": "/images/toyota/corolla-hybridle.png",
    "corolla-se": "/images/toyota/corolla-se.png",
    "corolla-fx": "/images/toyota/corolla-fx.png",
    "corolla-xse": "/images/toyota/corolla-xse.png",
    "corolla-hybridxle": "/images/toyota/corolla-hybridxle.png",
    "corolla-hybridse": "/images/toyota/corolla-hybridse.png",
  },
}

export const carImages = {
  bmw: {
    logo: "/images/bmw/bmw-logo.svg",
    background: "/images/bmw/bmw-background.jpg",
    models: {
      "bmw-m5": "/images/bmw/bmwm5.jpg",
      "bmw-x3": "/images/bmw/bmwx3.jpg",
      "bmw-x3m": "/images/bmw/bmwx3m.jpg",
      "bmw-x4": "/images/bmw/bmwx4.jpg",
      "bmw-x4m": "/images/bmw/bmwx4m.jpg",
      "bmw-x5": "/images/bmw/bmwx5.jpg",
      "bmw-x5m": "/images/bmw/bmwx5m.jpg",
      "bmw-x6": "/images/bmw/bmwx6.jpg",
      "bmw-x6m": "/images/bmw/bmwx6m.jpg",
      "bmw-x7": "/images/bmw/bmwx7.jpg",
      "bmw-er2": "/images/bmw/bmwer2.jpg",
      "bmw-er3": "/images/bmw/bmwer3.jpg",
      "bmw-er3m": "/images/bmw/bmwer3m.jpg",
      "bmw-er4": "/images/bmw/bmwer4.jpg",
      "bmw-er4m": "/images/bmw/bmwer4m.jpg",
      "bmw-er4cupe": "/images/bmw/bmwer4cupe.jpg",
      "bmw-er7": "/images/bmw/bmwer7.jpg",
      "bmw-er7m": "/images/bmw/bmwer7m.jpg",
      "bmw-er8coupe": "/images/bmw/bmwer8coupe.jpg",
      "bmw-er8m": "/images/bmw/bmwer8m.jpg",
      "bmw-er8carbio": "/images/bmw/bmwer8carbio.jpg"
    }
  },
  audi: {
    logo: "/images/audi/audi-logo.svg",
    background: "/images/audi/audi-background.jpg",
    models: {
      "audi-a3": "/images/audi/audia3.jpg",
      "audi-a4": "/images/audi/audia4.jpg",
      "audi-a5": "/images/audi/audia5.jpg",
      "audi-a6": "/images/audi/audia6.jpg",
      "audi-a8": "/images/audi/audia8.jpg",
      "audi-tt": "/images/audi/auditt.jpg",
      "audi-q3": "/images/audi/audiq3.jpg",
      "audi-q4-etron": "/images/audi/audiq4etron.jpg",
      "audi-q5": "/images/audi/audiq5.jpg",
      "audi-q8": "/images/audi/audiq8.jpg",
      "audi-q8-etron": "/images/audi/audiq8etron.jpg",
      "audi-r8": "/images/audi/audir8.jpg",
      "audi-rs7": "/images/audi/audirs7.jpg",
      "audi-etron-gt": "/images/audi/audietrongt.jpg",
      "audi-allnewa5": "/images/audi/allnewa5.jpg"
    }
  },
  toyota: {
    logo: "/images/toyota-logo.svg",
    background: "/images/toyota_bg.webp",
    models: {
      "toyota-corolla-le": "/images/toyota/corolla-le.png",
      "toyota-corolla-hybrid-le": "/images/toyota/corolla-hybridle.png",
      "toyota-corolla-se": "/images/toyota/corolla-se.png",
      "toyota-corolla-fx": "/images/toyota/corolla-fx.png",
      "toyota-corolla-xse": "/images/toyota/corolla-xse.png",
      "toyota-corolla-hybrid-xle": "/images/toyota/corolla-hybridxle.png",
      "toyota-corolla-hybrid-se": "/images/toyota/corolla-hybridse.png",
      "toyota-gr-supra-3.0": "/images/toyota/grsupra3.0.png",
      "toyota-gr-supra-3.0-premium": "/images/toyota/grsupra3.0-premium.png",
      "toyota-crown-platinum": "/images/toyota/crown-platinum.png",
      "toyota-crown-nightshade": "/images/toyota/crown-nightshade.png",
      "toyota-crown-limited": "/images/toyota/crown-limited.png",
      "toyota-crown-xle": "/images/toyota/crown-xle.png"
    }
  },
  mercedesbenz: {
    logo: "/images/mercedesbenz/mercedes-logo.svg",
    background: "/images/mercedesbenz/mercedes-background.jpg",
    models: {
      "mercedes-amg-gt": "/images/mercedesbenz/mercedesamggt.jpg",
      "mercedes-cle200-amgline-cabriolet": "/images/mercedesbenz/cle200amglinecabriolet.jpg",
      "mercedes-cle200-amgline-coupe": "/images/mercedesbenz/cle200amglinecoupe.jpg",
      "mercedes-cle200-amgline-premium-cabriolet": "/images/mercedesbenz/cle200amglinepremiumcabriolet.jpg",
      "mercedes-cle200-amgline-premium-coupe": "/images/mercedesbenz/cle200amglinepremiumcoupe.jpg",
      "mercedes-cle200-amgline-premiumplus-cabriolet": "/images/mercedesbenz/cle200amglinepremiumpluscabriolet.jpg",
      "mercedes-cle200-amgline-premiumplus-coupe": "/images/mercedesbenz/cle200amglinepremiumpluscoupe.jpg",
      "mercedes-cle200d-amgline-cabriolet": "/images/mercedesbenz/cle200damglinecabriolet.jpg",
      "mercedes-cle200d-amgline-coupe": "/images/mercedesbenz/cle200damglinecoupe.jpg",
      "mercedes-cle200d-amgline-premium-cabriolet": "/images/mercedesbenz/cle200damglinepremiumcabriolet.jpg",
      "mercedes-cle200d-amgline-premium-coupe": "/images/mercedesbenz/cle200damglinepremiumcoupe.jpg",
      "mercedes-cle220d-amgline-premium-cabriolet": "/images/mercedesbenz/cle220damglinepremiumcabriolet.jpg",
      "mercedes-cle220d-amgline-premiumplus-cabriolet": "/images/mercedesbenz/cle220damglinepremiumpluscabriolet.jpg",
      "mercedes-cle220d-amgline-premiumplus-coupe": "/images/mercedesbenz/cle220damglinepremiumpluscoupe.jpg",
      "mercedes-cle300-4matic-amgline-premium-coupe": "/images/mercedesbenz/cle3004maticamglinepremiumcoupe.jpg"
    }
  }
} as const

